In [17]:
import numpy as np
a=[1,2,3]
np.mean(a)

np.float64(2.0)

In [ ]:
import random
arr=np.array([random.randint(0,250) for i in range(30000)], dtype=np.uint8).reshape(100,100,3)
ix=sorted(list(range(100))*2)
arr_new=arr[ix][:,ix]
# print(arr)
print(arr_new)

[[ 65 123  74]
 [ 65 123  74]
 [158  52 180]
 [158  52 180]
 [140 234 197]
 [140 234 197]
 [ 71 225 111]
 [ 71 225 111]
 [196 213 132]
 [196 213 132]
 [ 24  28 127]
 [ 24  28 127]
 [127  19 225]
 [127  19 225]
 [ 36  76 200]
 [ 36  76 200]
 [ 29  82  70]
 [ 29  82  70]
 [ 26 228 143]
 [ 26 228 143]
 [ 31 168   1]
 [ 31 168   1]
 [176  46 134]
 [176  46 134]
 [194 150  50]
 [194 150  50]
 [ 90 100  89]
 [ 90 100  89]
 [105  74 132]
 [105  74 132]
 [166  38 183]
 [166  38 183]
 [221  93 106]
 [221  93 106]
 [130  77 173]
 [130  77 173]
 [ 60 110  62]
 [ 60 110  62]
 [ 40  13  61]
 [ 40  13  61]
 [185 203  32]
 [185 203  32]
 [ 10 147 101]
 [ 10 147 101]
 [ 82 179 208]
 [ 82 179 208]
 [ 30 224 110]
 [ 30 224 110]
 [186 216 240]
 [186 216 240]
 [ 76 199 131]
 [ 76 199 131]
 [  9  44 161]
 [  9  44 161]
 [236 179 198]
 [236 179 198]
 [198  93 142]
 [198  93 142]
 [ 47 215 226]
 [ 47 215 226]
 [ 35 152 149]
 [ 35 152 149]
 [165  97 140]
 [165  97 140]
 [ 16  51  11]
 [ 16  51  11]
 [196 190 

In [35]:
from PIL import Image
image=Image.fromarray(arr_new)
display(image)
